// <auto-generated />
namespace DynamicMVC.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class notes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notes));
        
        string IMigrationMetadata.Id
        {
            get { return "201602211555076_notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
