namespace DynamicMVC.Shared.Enums
{
    public enum SimpleTypeEnum
    {
        Bool,
        BoolNullable,
        Byte,
        ByteNullable,
        Char,
        CharNullable,
        DateTime,
        DateTimeNullable,
        Decimal,
        DecimalNullable,
        Double,
        DoubleNullable,
        Float,
        FloatNullable,
        Guid,
        GuidNullable,
        Int16,
        Int16Nullable,
        Int32,
        Int32Nullable,
        Int64,
        Int64Nullable,
        SByte,
        SByteNullable,
        String,
        UInt16,
        UInt16Nullable,
        UInt32,
        UInt32Nullable,
        UInt64,
        UInt64Nullable
    }
}
